empleados/applications/persona/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-empleados-area/<short_name>', views.ListByArea.as_view(), name='empleados_by_area'),
    path('listar-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_by_lista'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(),name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='add_empleado'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleados/empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    path('departamento/', include('applications.departamento.urls')),
    path('persona/', include('applications.persona.urls')),
    path('', include('applications.home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleados/applications/persona/models.py
from distutils.command.upload import upload
from django.db import models
from applications.departamento.models import DepartamentoModelo
# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)
    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidad Empleados'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad


class Empleado(models.Model):
    #Modelo para la tabla empleado
    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre completo', max_length=120,blank=True)
    job = models.CharField('Trabajo',max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(DepartamentoModelo, on_delete=models.CASCADE)
    #para una relacion de muchos a muchos
    habilidades = models.ManyToManyField(Habilidades)
    avatar = models.ImageField(upload_to='empleado',blank=True,null=True)

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

empleados/applications/persona/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from .models import Empleado, DepartamentoModelo, Habilidades
# Create your views here.

class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering = 'first_name'

    def get_queryset(self):
        #aqui obtengo el input del html a traves de un get
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
            #Buscamos por cadena, ejemplo= si buscamos jo el icontains se encargara de buscar todos los nombres
            #que contangan la j y la o al principio
            full_name__icontains=palabra_clave
        )
        return lista
    
    
class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/list_empleados_admin.html'
    paginate_by = 10
    ordering = 'first_name'
    model = Empleado


class ListByArea(ListView):
    #Listar empleados de un area
    template_name = 'persona/list_by_area.html'

    def get_queryset(self):
        parametro = self.kwargs["short_name"]
        lista = Empleado.objects.filter(
        departamento__short_name = parametro
    )
        return lista


class ListEmpleadosByKword(ListView):
    #lista de empleados por palabra clave
    template_name='persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        #aqui obtengo el input del html a traves de un get
        palabra_clave = self.request.GET.get("kword", "")
        print ('=====', palabra_clave)
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
        return lista

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"


class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    #fields = ['first_name','last_name','job']
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'avatar',
    ]

    #validacion de los datos
    def form_valid(self, form):
        empleado = form.save()
        #aqui completo los datos del full name concatenando el first_name y el last_name
        empleado.full_name = empleado.first_name + '' + empleado.last_name
        
        print(empleado.first_name)
        return super(EmpleadoCreateView, self).form_valid(form)
    success_url = reverse_lazy('persona_app:correcto')


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = ('__all__')
    success_url = reverse_lazy('persona_app:correcto')

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:correcto')
    

empleados/templates/persona/add.html
{% extends "base.html" %}

{% block title %}
  Registrar Empleado
{% endblock title %}

{% block content %}
{% include "includes/header.html" %}
 
 <div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="medium-6 cell">
                <label>
                    Nombres:
                    {{ form.first_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>
                    Apellidos:
                    {{ form.last_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>
                    Trabajo:
                    {{ form.job }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>
                    Departamento:
                    {{ form.departamento }}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>
                    Habilidades:
                    {{ form.habilidades }}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>
                    Habilidades:
                    {{ form.avatar }}
                </label>
            </div>
            <div class="medium-6 cell">
                <button class="button success" type="submit">Agregar</button>
            </div>
            <!--Puedo utilizar este atributo gracias a la CreateView-->
        </form>
    </div>
</div>
{% endblock content %}

empleados/templates/persona/by_kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Buscar empleado por palabra clave</h1>
    <form method="GET">
        {% csrf_token %}
        <input type="text" id="kword" name="kword" placeholder="Ingrese un nombre">
        <button type="submit">Buscar</button>
    </form>

    <h3>Lista de resultados</h3>

    {% for e in empleados %}

        <li>{{e}}</li>
      
    {% endfor %}
    
</body>
</html>

empleados/templates/persona/by_parameter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Buscar habilidades de empleado por parametro</h1>
    {% for e in habilidades %}

        <li>{{e}}</li>
      
    {% endfor %}
</body>
</html>

empleados/templates/persona/delete.html
{% extends "base.html" %} 
{% block title %} 
    Eliminar Empleado
{% endblock title%} 

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
  <div class="grid-x">
    <h1></h1>
    <form class="cell" method="POST">{% csrf_token %}
        <h3>¿Quiere eliminar este empleado? {{ object.full_name }}</h3>
        <div class="callout secondary">
            <p p>confirme que desea eliminar</p>
            <button class="alert button" type="submit">Confirmar</button>      
          </div>
      
    </form>
  </div>
</div>

{% endblock content %}

empleados/templates/persona/detail_empleado.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ object.full_name }}
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
                <!-- Mostrando el nombre y no el numero de los job -->
              {{ empleado.get_job_display }}
            </div>
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">  
            {% else %}
                <img src="{% static 'img/default.jpg' %}">
            {% endif %}
            
            <div class="card-section">
              <h4>{{ empleado.full_name}}</h4>
              <p>{{ empleado.departamento.short_name }}</p>
              <p><span class="label">Habilidades:</span></p>
              <ul class="vertical menu">
                {% for h in empleado.habilidades.all %}
                  <li>
                    {{ h.habilidad }} 
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
    </div>
</div>
  
{% endblock content %}

empleados/templates/persona/list_all.html
{% extends "base.html" %} 

{% block content %}

    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista empleados</h1>
            <form class="cell grid-x" method="GET">
                {% csrf_token %}
                <div class="cell large-7">
                    <input id="kword" name="kword" type="text" placeholder="Buscar Empleado">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="button secondary">Buscar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>

                      <tr>
                        <th width="50">ID</th>
                        <th width="100">NOMBRES</th>
                        <th width="100">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                      </tr>
                    </thead>
                    <tbody><!-- itero la lista de empleados con un for y saco cada data accediendo a los
                            atributos de los modelos-->
                    {% for e in object_list %}
                      <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <!-- Anadiendo url al html con un nombre y una pk que le fueron asignadas en el urls.py -->
                        <td><a class="button primary" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                      </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- Paginacion de lista -->
            <div class="cell">
              {% if is_paginated %}
              <nav aria-label="Pagination">
                <ul class="pagination text-center">
                  {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                     <a href="?page={{ page_obj.previous_page_number }}">Previous</a> 
                    </li>  
                  {% endif %}

                  <!-- iterando las paginas para mostrarlas -->
                  {% for pagina in paginator.page_range %}

                  {% if pagina == page_obj.number %}
                      <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                  {% else %}
                    <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>  
                  {% endif %}
                  {% endfor %}
                  
                  {% if page_obj.has_next %}
                    <li class="pagination-next">
                      <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next</a>
                    </li>
                    
                  {% endif %}
                  
                </ul>
              </nav>  
              {% endif %}
            </div>
        </div>
{% endblock content %}

empleados/templates/persona/list_by_area.html
{% extends "base.html" %}

{% block title %}
  Lista de Empleados por Departamento
{% endblock title %}

{% block content %}
  {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell"><h3>Empleados por area</h3></div>
            <div class="cell">
                <div class="cell">
                    <table>
                        <thead>
    
                          <tr>
                            <th width="50">ID</th>
                            <th width="100">NOMBRES</th>
                            <th width="100">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCION</th>
                          </tr>
                        </thead>
                        <tbody><!-- itero la lista de empleados con un for y saco cada data accediendo a los
                                atributos de los modelos-->
                        {% for e in object_list %}
                          <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <!-- Anadiendo url al html con un nombre y una pk que le fueron asignadas en el urls.py -->
                            <td><a class="button primary" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                          </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

empleados/templates/persona/list_empleados_admin.html
{% extends "base.html" %} 

{% block content %}

    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista empleados</h1>
            <div class="cell">
                <table>
                    <thead>

                      <tr>
                        <th width="50">ID</th>
                        <th width="150">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="100">ACCION</th>
                      </tr>
                    </thead>
                    <tbody><!-- itero la lista de empleados con un for y saco cada data accediendo a los
                            atributos de los modelos-->
                    {% for e in object_list %}
                      <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <!-- Anadiendo url al html con un nombre y una pk que le fueron asignadas en el urls.py -->
                        <td>
                            <a class="button small warning" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                            <a class="button small alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                      </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- Paginacion de lista -->
            <div class="cell">
              {% if is_paginated %}
              <nav aria-label="Pagination">
                <ul class="pagination text-center">
                  {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                     <a href="?page={{ page_obj.previous_page_number }}">Previous</a> 
                    </li>  
                  {% endif %}

                  <!-- iterando las paginas para mostrarlas -->
                  {% for pagina in paginator.page_range %}

                  {% if pagina == page_obj.number %}
                      <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                  {% else %}
                    <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>  
                  {% endif %}
                  {% endfor %}
                  
                  {% if page_obj.has_next %}
                    <li class="pagination-next">
                      <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next</a>
                    </li>
                    
                  {% endif %}
                  
                </ul>
              </nav>  
              {% endif %}
            </div>
        </div>
{% endblock content %}

empleados/templates/persona/success.html
{% extends "base.html" %}

{% block title %}
  Accion Exitosa
{% endblock title %}

{% block content %}
    <h1>Registro guardado.</h1>
    <button>
        <a class="button primary" href="{% url 'persona_app:empleados_by_lista' %}">Volver</a>
    </button>
{% endblock content %}
    

empleados/templates/persona/update.html
{% extends "base.html" %}

{% block title %}
    Editar Empleado
{% endblock title %}

{% block content %}
  {% include "includes/header.html" %}

  <div class="grid-container">
      <div class="grid-x">
          <h1 class="cell">
              Modificar Empleado
          </h1>
          <div class="cell">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
          
                <button class="button success" type="submit">Actualizar</button>
            </form>
          </div>
      </div>
  </div>
{% endblock content %}

    