empleados/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='departamento_app'

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('listar-departamento/', views.DepartamentoListView.as_view(), name='listar_departamento'),
]

empleados/applications/persona/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-empleados-area/<short_name>', views.ListByArea.as_view(), name='empleados_by_area'),
    path('listar-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_by_lista'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(),name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='add_empleado'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleados/empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    path('departamento/', include('applications.departamento.urls')),
    path('persona/', include('applications.persona.urls')),
    path('', include('applications.home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleados/applications/departamento/models.py
from django.db import models


# Create your models here.

class DepartamentoModelo(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre corto', max_length=20)
    anulate = models.BooleanField('Anulado',default=False)

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.short_name

empleados/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    nombre_corto = forms.CharField(max_length=20)

empleados/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.views.generic import ListView
from .forms import NewDepartamentoForm
from applications.persona.models import Empleado
from .models import DepartamentoModelo

# Create your views here.

class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = DepartamentoModelo
    

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = reverse_lazy('departamento_app:listar_departamento')

    def form_valid(self, form):
        print('formvalue')
        
        #1 manera de usar la ORM para guardar datos
        depa = DepartamentoModelo(
            name = form.cleaned_data['departamento'],
            short_name = form.cleaned_data['nombre_corto']
        )
        depa.save()

        #2 manera de usar la ORM para guardar datos
        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']

        Empleado.objects.create(
            first_name = nombre,
            last_name = apellidos,
            job = '1',
            departamento = depa 
        )
        return super(NewDepartamentoView, self).form_valid(form)

empleados/templates/departamento/lista.html
{% extends 'base.html' %}

{% block tittle %}
    Lista departamentos
{% endblock tittle %}

{% block content %}

    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamentos in object_list %}
                        <tr>
                            <td>{{ departamentos.name }}</td>
                            <td>{{ departamentos.short_name }}</td>
                            <td><a class="button primary" href="{% url 'persona_app:empleados_by_area' departamentos.short_name %}">Ver Empleados</a></td>
                        </tr>  
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
  
{% endblock content %}

empleados/templates/departamento/new_departamento.html
{% extends "base.html" %}

{% block title %}
  Registrar Departamento
{% endblock title %}

{% block content %}
{% include "includes/header.html" %}
 
 <div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">
            {% csrf_token %}
            <div class="medium-6 cell">
                <label>
                    Nombre Empleado:
                    {{ form.nombre }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>
                    Apellidos Empleado:
                    {{ form.apellidos }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>
                    Nombre Departamento:
                    {{ form.departamento }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>
                    Nombre Corto Departamento:
                    {{ form.nombre_corto }}
                </label>
            </div>
            <div class="medium-6 cell">
                <button class="button success" type="submit">Agregar</button>
            </div>
            <!--Puedo utilizar este atributo gracias a la CreateView-->
        </form>
    </div>
</div>
{% endblock content %}