empleados/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='departamento_app'

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('listar-departamento/', views.DepartamentoListView.as_view(), name='listar_departamento'),
]

empleados/applications/persona/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-empleados-area/<short_name>', views.ListByArea.as_view(), name='empleados_by_area'),
    path('listar-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_by_lista'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(),name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='add_empleado'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleados/empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    path('departamento/', include('applications.departamento.urls')),
    path('persona/', include('applications.persona.urls')),
    path('', include('applications.home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleados/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <!-- Anadiendo la ulr a traves del nombre que se le asigno en urls.py -->
          <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:listar_departamento' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:empleados_by_lista' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a href="{% url 'persona_app:add_empleado' %}" class="button">Registrar nuevo</a></li>
      </ul>
    </div>
  </div>